name: TptpPlugin
version: ${project.version}
main: me.zbenjamin.tptpplugin.TptpPlugin
api-version: 1.14
authors: [ZBenjamin]
description: Warping and emotes
commands:
  sad:
    description: Legyél szomorú. Be sad.
    usage: /<command> [online player]
    aliases: [szomoru]
  happy:
    description: Legyél boldog. Be happy.
    usage: /<command> [online player]
    aliases: [boldog]
  tptpconfig:
    description: Konfigurálni tudod a plugint. You can set the plugin's config.
    usage: /<command> <set <key> <value> | reload | save>
  tptpset:
    description: TP pontokat tudsz elmenteni, akár csak saját magadnak is. You can save TP points, even only for yourself.
    usage: /<command> <név/name> [x] [y] [z] [self]
  tptp:
    description: Az elmentett TP pontokra tudsz teleportálni. You can teleport to saved TP points.
    usage: /<command> <név/name>
  tptpsign:
    description: Egy táblát warp-táblává alakít át. It makes a sign to a warp-sign.
    usage: /<command>
  lobby:
    description: Elteleportál a lobbyba, vagy beállítja azt. It teleports you to the lobby, or you can set it.
    usage: /<command> [set [x] [y] [z] | reloadconfig | setprotect <p1 | p2> | protect <on | off>]
  rename:
    description: Át tudod nevezni a kezedben lévő tárgyat. You can rename the item in your main hand.
  getcoord:
    description: Kiírathatod a koordinátád a chatbe. You can broadcast your coordinate.
  blockcoord:
    description: Lekérheted a blokk koordinátáját, amire nézel. You can get the coordinate of the block that you're looking.
  heal:
    description: Feltölti az életpontjaid. It sets the maximum health points.
    usage: /<command> [online player]
  feed:
    description: Feltölti az ételpontjaid. It sets the maximum food points.
    usage: /<command> [online player]
  invulnerable:
    description: Beállíthatsz sérthetetlenséget. You can set invulnerability.
    usage: /<command> <true/false> [online player]
  gcmd:
    description: Ad egy parancsblokkot. It gives you a command block.
  gbarr:
    description: Ad egy barriert. It gives you a barrier.