name: TptpPlugin
version: ${project.version}
main: me.zbenjamin.tptpplugin.TptpPlugin
api-version: 1.14
authors: [ZBenjamin]
description: Warping and emotes
commands:
  sad:
    description: Legyél szomorú.
    usage: /<command> <player>
    aliases: [szomoru]
  happy:
    description: Legyél boldog.
    usage: /<command> <player>
    aliases: [boldog]
